/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CameraIcon: typeof import('./src/components/icons/CameraIcon.vue')['default']
    GalleryIcon: typeof import('./src/components/icons/GalleryIcon.vue')['default']
    MapIcon: typeof import('./src/components/icons/MapIcon.vue')['default']
    ProfileIcon: typeof import('./src/components/icons/ProfileIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
